# Prepare a pool of CI scratch orgs

name: 'Replenish CI Pools - Auto Triggered'
trigger: none
pr: none

schedules:
    - cron: '0 0 * * *'
      displayName: Daily midnight prepare pool
      branches:
          include:
              - azp-templates
      always: true

pool:
    vmImage: 'ubuntu-latest'

container: dxatscale/sfpowerscripts:latest

variables:
  - group: SalesforceCICD

steps:    

    - script: |
          echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub
      displayName: 'Authenticate DevHub'

    - task: DownloadSecureFile@1
      name: npmrc
      inputs:
          secureFile: .npmrc

    - task: npmAuthenticate@0
      inputs:
        workingFile: (npmrc.secureFilePath)

    - script: |
          sfdx sfpowerscripts:orchestrator:prepare -f config/cipool.json -v devhub
      displayName: 'Prepare a pool of scratch orgs'

    - task: CopyFiles@2
      inputs:
            contents: '.sfpowerscripts/prepare_logs/**'
            targetFolder: $(Build.ArtifactStagingDirectory)
            
    - task: PublishBuildArtifacts@1
      inputs:
            pathToPublish: $(Build.ArtifactStagingDirectory)
            artifactName: PrepareLogs