name: Release

trigger: none
pr: none

stages:
    - stage: release
      displayName: release
      jobs:
          - job: release
            displayName: release
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest
            steps:
                - checkout: self
                  persistCredentials: true

                - task: DownloadSecureFile@1
                  name: npmrc
                  inputs:
                      secureFile: .npmrc

                - task: npmAuthenticate@0
                  inputs:
                    workingFile: $(npmrc.secureFilePath)

                - task: DownloadSecureFile@1
                  name: devhubKey
                  inputs:
                      secureFile: 'DEVHUB_SERVER_KEY'

                - script: |
                      sfdx auth:jwt:grant -u $(DEVHUB_USERNAME) -i $(DEVHUB_CLIENT_ID) -f $(devhubKey.secureFilePath) -a devhub -r https://login.salesforce.com
                  displayName: 'Authenticate DevHub'

                - task: CmdLine@2
                  displayName: 'Create ScratchOrg'
                  inputs:
                      script: 'sfdx force:org:create -f config/project-scratch-def.json -a scratch-org -s -d 1 -v devhub'

                - task: CmdLine@2
                  displayName: 'Deploy packages to scratch org'
                  inputs:
                      script: 'sfdx sfpowerscripts:orchestrator:release -u scratch-org -p .azure-pipelines/releaseDefinitions/releaseDefinition.yml --npm --scope dxatscale --npmrcpath $(npmrc.secureFilePath) --generatechangelog'

                - task: CmdLine@2
                  displayName: 'Delete scratch org'
                  condition: always()
                  inputs:
                      script: 'sfdx force:org:delete -p -u scratch-org'
