# Validate changes introduced through PR

trigger: none

pr:
    autoCancel: false
    drafts: false
    branches:
        include:
            - azp-templates
variables:
  - group: SalesforceCICD

stages:
    - stage: ValidatePMD
      displayName: ValidatePMD
      dependsOn: []
      jobs:
          - job: ValidatePMD
            displayName: 'Validate PMD'
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest         

            steps:

            - checkout: self
              persistCredentials: true
      
            - script: |
                  npx sfdx sfpowerkit:source:pmd -f csv --reportfile pmd-output.csv --no-failonviolation
              continueOnError: true
              displayName: 'PMD Validation'  

    - stage: ValidateSource
      displayName: 'Validate Source'
      dependsOn: []
      jobs:
          - job: ValidateSource
            displayName: 'Validate Source'
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest     

            steps:

            - checkout: self
              persistCredentials: true
                
            - script: |
                    echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
                    sfdx auth:sfdxurl:store -f authfile -a devhub
              displayName: 'Authenticate DevHub'

            - script: |
                    npx sfdx sfpowerscripts:orchestrator:validate -x -p ci -v devhub --loglevel debug
              displayName: 'Validate Source'
