# Validate changes introduced through PR

trigger: none

pr:
    autoCancel: false
    drafts: false
    branches:
        include:
            - azp-templates
variables:
  - group: SalesforceCICD

stages:
    - stage: ValidatePMD
      displayName: ValidatePMD
      dependsOn: []
      jobs:
          - job: ValidatePMD
            displayName: 'Validate PMD'
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest         

            steps:

            - checkout: self
              persistCredentials: true
      
            - script: |
                  sfdx sfpowerscripts:analyze:pmd -b  -o pmd-output
              continueOnError: true
              displayName: 'PMD Validation'  

            - task: PublishBuildArtifacts@1
              inputs:
                    pathToPublish: pmd-output/
                    artifactName: PrepareLogs


    - stage: ValidateSource
      displayName: 'Validate Source'
      dependsOn: []
      jobs:
          - job: ValidateSource
            displayName: 'Validate Source'
            pool:
                vmImage: 'ubuntu-latest'
            container: dxatscale/sfpowerscripts:latest     

            steps:

            - checkout: self
              persistCredentials: true
                
            - script: |
                    echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
                    sfdx auth:sfdxurl:store -f authfile -a devhub
              displayName: 'Authenticate DevHub'

            - script: |
                    npx sfdx sfpowerscripts:orchestrator:validate -x -p ci -v devhub --loglevel debug
              displayName: 'Validate Source'
