# Validate changes introduced through PR

trigger: none

pr:
    autoCancel: false
    drafts: false
    branches:
        include:
            - azp-templates
pool:
    vmImage: 'ubuntu-latest'

container: dxatscale/sfpowerscripts:latest

variables:
  - group: SalesforceCICD

steps:

    - checkout: self
      persistCredentials: true
      
    - script: |
          echo $(DEVHUB_SFDX_AUTH_URL) > ./authfile
          sfdx auth:sfdxurl:store -f authfile -a devhub
      displayName: 'Authenticate DevHub'

    - script: |
       npx sfdx sfpowerkit:source:pmd -f csv --reportfile pmd-output.csv --no-failonviolation
       continueOnError: true
       displayName: 'PMD Validation'

    - script: |
       sfdx sfpowerscripts:orchestrator:validate -x -p CI -v devhub --loglevel debug
       displayName: 'Validate Source'
